"""Protocol version history from git: every commit that changed PROTOCOL.md, with its time and protocol version.

Writes reports/protocol_history.md. Commit times are recorded by the author's computer, so this table shows the order
of commits, not an independent timestamp.
"""

import argparse
import subprocess
from pathlib import Path

import pandas as pd

from seer_study.manuscript import protocol_version
from seer_study.report import assert_style, md_table


def git(*args: str) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True, check=True).stdout


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protocol", default="PROTOCOL.md")
    parser.add_argument("--output", type=Path, default=Path("reports/protocol_history.md"))
    args = parser.parse_args()

    rows = []
    for line in git("log", "--reverse", "--format=%h|%ad|%s", "--date=iso", "--", args.protocol).splitlines():
        commit, date, subject = line.split("|", 2)
        rows.append({
            "commit": commit,
            "commit time (author's computer)": date,
            "protocol version": protocol_version(git("show", f"{commit}:{args.protocol}")) or "not stated",
            "commit message": subject,
        })
    remote = git("remote", "get-url", "origin").strip() if "origin" in git("remote").split() else "no remote"
    text = "\n\n".join([
        "# Protocol version history",
        f"Generated by `scripts/protocol_history.py` from the git history of `{args.protocol}` (remote: {remote}). Commit "
        "times are recorded by the author's computer and are not independent timestamps; the table shows the order in which "
        "protocol versions were committed.",
        "## Protocol versions by commit",
        md_table(pd.DataFrame(rows)),
    ]) + "\n"
    assert_style(text)
    args.output.write_text(text)
    print(args.output)


if __name__ == "__main__":
    main()
